ls #Basic command to show a list of content in a directory. If you wanna see a hiding files you can use "ls -la" including the files starting with "."
ls /dev #Files of device, everything in linux is a file.
ls /proc #List with the information about the process generated by the RAM memory. 
cat /proc/cpuinfo #Show a detail information about the CPU.
ls /bin  #List of a executable files in binary(bin).
type zsh #An executable in the binary folder. Useful to know the command is a shell function or a executable file. Like /usr/bin/zsh
ls /home #Where save the personal users folders. Only the root can access the /root directory.
ls /codespaces #Specific folder of cloud service (GitHub Codespace) where you save are your work.

gcc saludo.c -o saludo_bin #Call the gcc compiler to transfrom the code of saludo.c to an executable binary file called saludo_bin
cp saludo_bin /bin/saludo_bin #copy the binary executable in the system commands folder (/bin).
sudo cp saludo_bin /bin/saludo_bin #To do it, need permission so if the last command dosent work use sudo to execute the command like a root.
cd / #root, move you to the high livel or administrator.
saludo_bin #execute the command, and print the messsage "Hello World!", this message are the same in the print line in saludo.c.
cd /home/codespace #Chace directory to /home/codespaces.

ls -i #List of files with each "inode" number (unique identificator of each file)
ls -f #List of files with non order. 
pwd #(Print World Directory), print the directory where I am working

echo "Hola" > test.txt #Use echo to can show it into the terminal, and the message in "" put in a .txt file.
stat test.txt #provides a snapshot of the file's metadata.
